version: '1'

services:
  web: 
    build:
      context: .
      dockerfile: .build/werkzeug.DockerFile
    stop_signal: SIGINT
    command: python src/run.py
    ports:
      - "5000:5000"
    depends_on:
      - postgre_db
  postgre_db:
    build:
      context: .
      dockerfile: .build/postgre.DockerFile
    ports:
      - "5432:5432"